version: 2.1
orbs:
  node: circleci/node@5.1.0
  aws-cli: circleci/aws-cli@2.1.0
  aws-elastic-beanstalk: circleci/aws-elastic-beanstalk@2.0.1
jobs:
  build:
    docker:
      - image: 'cimg/base:stable'
    steps:
      - node/install
      - checkout
      - aws-cli/setup
      - aws-elastic-beanstalk/setup
      - run:
          name: API Install
          command: |
            npm run api:install
      - run:
          name: Front-End Install
          command: |
            npm run frontend:install
      - run:
          name: API Build
          command: |
            npm run api:build
      - run:
          name: Front-End Build
          command: |
            npm run frontend:build
      - run:
          name: Front-End Test
          command: |
            npm run frontend:test
      - run:
          name: Deploy API
          command: |
            npm run api:deploy
      - run:
          name: Deploy Front-End
          command: |
            npm run frontend:deploy
workflows:
  udagram:
    jobs:
      - build:
        filter:
          branches:
            only:
              - master  